name = "ImpedanceTomography"
uuid = "896e9044-b25c-4c80-8668-1ae27bcd2be0"
authors = ["Stratos Staboulis <stratos.staboulis@leanheat.com>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
